# Generated by Django 3.2.5 on 2021-08-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventscalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=12)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_planner', models.CharField(max_length=25)),
                ('event_participant', models.CharField(max_length=25)),
                ('event_duration', models.TimeField()),
                ('event_approved_by', models.CharField(max_length=25)),
                ('event_id', models.CharField(max_length=25)),
            ],
        ),
    ]
