# Generated by Django 3.2.5 on 2021-08-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=15)),
                ('course_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('no_of_lessons_taught', models.PositiveBigIntegerField()),
                ('profile', models.ImageField(upload_to='')),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=10)),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('cv', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=25)),
                ('contract', models.FileField(upload_to='')),
                ('date_hired', models.DateField(max_length=10)),
                ('language', models.CharField(choices=[('E', 'English'), ('E', 'Swahili'), ('E', 'Kinyarwanda'), ('E', 'French'), ('E', 'Kiganda')], max_length=1)),
            ],
        ),
    ]
