# Generated by Django 3.2.5 on 2021-08-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('course_code', models.CharField(max_length=25)),
                ('syllabus', models.CharField(max_length=15)),
                ('course_trainer', models.CharField(max_length=25)),
                ('course_schedule', models.FileField(upload_to='')),
                ('course_duration', models.CharField(max_length=10)),
            ],
        ),
    ]
